### ISSUE TITLE
How to configure `app-settings.json`?

### ISSUE THREAD

**Issue by Waog** [vladimir-kotikov/cordova-app-preferences#1]
Hi and thanks for this great plugin.

What are legal contents for the `app-settings.json`?

Is it a general format I can read about elsewhere? Or is it's content special for this cordova plugin? Where can I find more information? What are the search terms I need, to find out more?

Thanks in advance :)

**Comment by vladimir-kotikov** [comment]
Hey @Waog. This repo is just a fork that was created for my own purposes, so I think you'd better to ask this question in original repo: https://github.com/apla/me.apla.cordova.app-preferences

**Comment by Waog** [comment]
Thx @vladimir-kotikov. Don't know how I got redirected here.

I re-asked the [issue in the original repo](https://github.com/apla/me.apla.cordova.app-preferences/issues/122)
